export const CHANGE_SELECTED_SCHOOL = "CHANGE_SELECTED_SCHOOL";
export const CHANGE_SELECTED_TEACHER = "CHANGE_SELECTED_TEACHER";
export const FILTER_TABLE_BY_SCHOOL = "FILTER_TABLE_BY_SCHOOL";
export const FILTER_TABLE_BY_TEACHER = "FILTER_TABLE_BY_TEACHER";
